version: 2
updates:
- package-ecosystem: npm
  directory: "/backend"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
